### ISSUE TITLE
{:ssl_closed, _} leaking from Hackney into oc_reporter

### ISSUE THREAD

**Issue by astutecat** [opencensus-beam/opencensus_honeycomb#4]
We've noticed that when using `opencensus_honeycomb` on our system that we've been getting the following happening:

`** (FunctionClauseError) no function clause matching in :oc_reporter.handle_info/2                                                                                                                   
Nov 06 11:40:42 ...compute.internal ...[4827]:     (opencensus) /.../oc_reporter.erl:105: :oc_reporter.handle_info({:ssl_closed, {:sslsocket, {:gen_tcp, #Port<0.17
519>, :tls_connection, :undefined}, [#PID<0.25634.163>, #PID<0.25891.163>]}}, {:state, [{Opencensus.Honeycomb.Reporter, :ok}], 1500, #Reference<0.4075178422.1500512257.140826>})`

We found this of particular concern because at points this crash was happening frequently enough that it would take down the VM.

We did an investigation and found the following open issue: https://github.com/benoitc/hackney/issues/464 and eventually, we got to this useful piece of information: https://github.com/benoitc/hackney/issues/464#issuecomment-552895496

I believe that the same issue that was affecting `oc_google_reporter` may also be affecting `opencensus_honeycomb` - I've got a code change that I hope will resolve it, but I've not been able to reproduce it to test it yet.

**Comment by garthk** [comment]
Nicely tracked down. Sorry I didn't spot this earlier; thanks for chasing it up within cooee of @tsloughter.

**Comment by garthk** [comment]
Published [v0.2.1](https://hex.pm/packages/opencensus_honeycomb/0.2.1).
